kind: pipeline
type: kubernetes
name: default



steps:
  - name: build
    image: docker
    commands:
      - docker build -t rahma/flask-tasks-app .



  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rahmamessadi23/flask-tasks-app
      tags: latest
