kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: docker
    environment:
      DOCKER_HOST: tcp://localhost:2375
    commands:
      - docker build -t rahma/flask-tasks-app .

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rahmamessadi23/flask-tasks-app
      tags: latest

services:
  - name: docker
    image: docker:dind
    privileged: true
    command: [ "dockerd-entrypoint.sh" ]
    args: [ "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock" ]

