kind: pipeline
type: kubernetes
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: rahmamessadi23/flask-tasks-app
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
