apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus   # ⚠️ doit matcher ton helm release
spec:
  groups:
    - name: example-alerts
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[5m])) by (pod) > 0.0005
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Pod {{ $labels.pod }} has CPU usage > 80% for more than 2 minutes."

        - alert: HighMemoryUsage
          expr: sum(container_memory_usage_bytes{image!=""}) by (pod) > 500000000
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High Memory usage detected"
            description: "Pod {{ $labels.pod }} is using more than 500MB memory."
