alertmanager:

  config:

    global:

      resolve_timeout: 5m

    route:

      receiver: demo-webhook

      group_wait: 5s

      group_interval: 10s

      repeat_interval: 1h

    receivers:

      - name: "null"

      - name: demo-webhook

        webhook_configs:

          - url: http://example.com/webhook

            send_resolved: true