apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-tasks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-tasks-app
  template:
    metadata:
      labels:
        app: flask-tasks-app
    spec:
      containers:
        - name: flask-tasks-app
          image: rahmamessadi23/flask-tasks-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          # Add environment variables
          env:
            - name: DATA_DIR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATA_DIR
            - name: TASKS_FILENAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASKS_FILENAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_MESSAGE
          volumeMounts:
            - name: tasks-volume
              mountPath: /data  # Must match ConfigMap value!
      volumes:
        - name: tasks-volume
          persistentVolumeClaim:
            claimName: tasks-pvc  # Use PVC instead of hostPath