version: "3"

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - 8000:80
    volumes:
      - drone-data:/data
    env_file:
      - .env
    environment:
      - DRONE_SERVER_HOST=localhost      # Assure-toi que le port est correct
      - DRONE_SERVER_PROTO=http
      - DRONE_GITHUB=true
      - DRONE_USER_CREATE=username:Messaadi-Rahma,admin:true

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}   # C’est très important que ça corresponde
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=local-runner

volumes:
  drone-data:

