apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/flask-tasks"  # Same as your hostPath location
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi