apiVersion: v1
kind: Service
metadata:
  name: flask-tasks-service
  labels:
    app: flask-tasks-app   # IMPORTANT : les labels
spec:
  type: NodePort
  selector:
    app: flask-tasks-app
  ports:
    - name: http           # 🔹 ajoute un nom ici
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
    - name: metrics        # 🔹 ajoute un deuxième port pour /metrics
      protocol: TCP
      port: 5001
      targetPort: 5001
