apiVersion: v1
kind: Service              # Type d’objet : Service Kubernetes

metadata:
  name: flask-tasks-service  # Nom du service

spec:
  type: NodePort           # Type d’accès : accessible depuis ton PC
  selector:                # Pour faire le lien avec les pods (grâce au label)
    app: flask-tasks-app

  ports:
    - protocol: TCP
      port: 5000           # Port interne du service (accès logique)
      targetPort: 5000     # Port sur lequel le conteneur écoute
      nodePort: 30001      # Port d’accès depuis l’extérieur (localhost:30001)
